site:
  title: Two Can Plugin Manual
  url:  https://nowhere.net
  start_page: twocan:ROOT:twocan.adoc
content:
  sources:
    - url: ../..
      start_path: manual/twocan/
      branches: HEAD
      edit_url: true
ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true
output:
  dir: ./docs
  clean: true              
