clone_folder: c:\project\ocpn_project
shallow_clone: false
clone_depth: 10

image:
- Visual Studio 2022

platform:
# - x64
  - Win32

configuration: Release
test: OFF

environment:
  OCPN_TARGET: MSVC

install:
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
    - set WX_VER=32
    - set WXWIN=C:\wxWidgets-3.2.1
    - set wxWidgets_ROOT_DIR=%WXWIN%
    - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
    - set cmake_parms=-A Win32
    - SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files\Poedit\Gettexttools\bin

    # install dependencies:
    - choco install poedit
    - choco install git
    - choco install wget

    # Download and unzip wxwidgets
    - wget -nv https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxMSW-3.2.1_vc14x_Dev.7z
    - wget -nv https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.1/wxWidgets-3.2.1-headers.7z
    - 7z x -o%WXWIN% wxMSW-3.2.1_vc14x_Dev.7z
    - 7z x -o%WXWIN% wxWidgets-3.2.1-headers.7z
    - set

before_build:
  - cd c:\project\ocpn_project
  - rm -rf build && mkdir build && cd build
  - cmake -A Win32 ..

build_script:
  - cmake --build . --target package --config Release
  - python -m ensurepip
  - python -m pip install -q setuptools
  - python -m pip install -q cloudsmith-cli
  - bash ../build/cloudsmith-upload.sh

artifacts:
  - path: 'build\*.exe'
    name: installer

