---
version: 2.1

parameters:
    run_workflow_deploy:
        type: boolean
        default: true


std-filters: &std-filters
    filters:
        branches:
            ignore:
            - devel
            - tmp
        tags:
            only: /.*/

workflows:
    build_all:
        jobs:

        - build-macos-wx32:
             <<: *std-filters
        - build-flatpak-arm64-2208:
            <<: *std-filters
        - build-flatpak-x86-2208:
            <<: *std-filters
        - build-debian-arm64-12-bookworm:
            <<: *std-filters
        - build-debian-armhf-12-bookworm:
            <<: *std-filters
        - build-debian-x86_64-12-bookworm:
            <<: *std-filters
        - build-ubuntu-x86_64-2204-jammy:
            <<: *std-filters

orbs:
    cloudsmith: cloudsmith/cloudsmith@1.0.4
    win: circleci/windows@5.0

commands:
    deploy-code:
        parameters:
            install-python:
                type: boolean
                default: false
            DEPLOY-USE-ORB:
                type: boolean
                default: true
        steps:
            - when:
                condition: <<pipeline.parameters.run_workflow_deploy>>
                steps:
                - when:
                    condition: <<parameters.install-python>>
                    steps:
                    - run: sudo apt install -y python3-pip
                    - run: python3.8 -m pip install cloudsmith-cli
                - when:
                    condition: <<parameters.DEPLOY-USE-ORB>>
                    steps:
                    - cloudsmith/ensure-api-key
                    - cloudsmith/install-cli
                - run: bash ci/cloudsmith-upload.sh

jobs:

    build-macos-wx32:
        macos:
            xcode: "15.2.0"
        environment:
        - OCPN_TARGET:  macos
        - CLOUDSMITH_PKG_EXT: pkg
        - WX_VER: "32"
        - DEPLOY_USE_ORB: false
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run: bash ci/circleci-build-macos.sh
        - deploy-code:
            deploy_use_orb: false
    build-flatpak-arm64-2208:
        machine:
            image: ubuntu-2004:202101-01
        resource_class: arm.medium
        environment:
        - OCPN_TARGET:  flatpak-arm64
        - FLATPAK_BRANCH: stable
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
        - deploy-code
    build-flatpak-x86-2208:
        machine:
            image: ubuntu-2004:202010-01
        environment:
        - OCPN_TARGET:  flatpak
        - FLATPAK_BRANCH: beta
        - CLOUDSMITH_PKG_EXT: gz
        - SDK_VER: 22.08
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: bash ci/circleci-build-flatpak.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-arm64-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=bookworm-arm64
        - DOCKER_IMAGE=arm64v8/debian:bookworm
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-armhf-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        resource_class: arm.medium
        environment:
        - OCPN_TARGET=bookworm-armhf
        - DOCKER_IMAGE=arm32v7/debian:bookworm
        - BUILD_FLAGS=-j3
        - BUILD_ENV=debian
        - WX_VER: 32
        - BUILD_GTK3: true
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-debian-x86_64-12-bookworm:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET: bookworm
        - BUILD_GTK3: true
        - WX_VER: 32
        - DEPLOY_USE_ORB: true
        - BUILD_ENV=debian
        - DOCKER_IMAGE=debian:bookworm
        steps:
        - checkout
        - run: chmod a+x ci/*.sh
        - run:
            command: ci/circleci-build-ubuntu-docker.sh
            no_output_timeout: 30m
        - deploy-code
    build-ubuntu-x86_64-2204-jammy:
        docker:
        - image: cimg/base:edge-22.04
        environment:
        - BUILD_GTK3: true
        - WX_VER: 32
        - OCPN_TARGET: jammy
        - DEPLOY_USE_ORB: true
        - BUILD_ENV=ubuntu
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ jammy-updates main" | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb [trusted=yes] https://ppa.launchpadcontent.net/bdbcat/opencpn/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x ci/*.sh
        - run: ci/circleci-build-debian.sh
        - deploy-code
   
   
