/* Autogenerated by png2wx.pl on Tue Apr 21 20:38:34 2020 */
#ifndef TWOCANICONS_H
#define TWOCANICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_Toucan_16;
extern wxBitmap *_img_Toucan_32;
extern wxBitmap *_img_Toucan_48;
extern wxBitmap *_img_Toucan_64;

#endif /* TWOCANICONS_H */
